version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=waffle_raise
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
