spring:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/waffle_raise
    username: root
    password: password
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:NONE}:3306/waffle_raise
    username: ${RDS_USERNAME:NONE}
    password: ${RDS_PASSWORD:NONE}
