spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/waffle_raise
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
