name: Deploy backend workflow

on:
  push:
    tags:
      - backend

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2
      ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      S3_SERVER_BUCKET: ${{ secrets.S3_SERVER_BUCKET }}
      EB_APPLICATION_NAME: waffleraise-server
      EB_ENV_NAME: waffleraise-server-env
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        id: login
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker image ls
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          aws s3 cp Dockerrun.aws.json s3://$S3_SERVER_BUCKET/Dockerrun.aws.json
          aws elasticbeanstalk create-application-version --application-name $EB_APPLICATION_NAME --version-label $IMAGE_TAG --source-bundle S3Bucket=$S3_SERVER_BUCKET,S3Key=Dockerrun.aws.json
          aws elasticbeanstalk update-environment --application-name $EB_APPLICATION_NAME --environment-name $EB_ENV_NAME --version-label=$IMAGE_TAG
