name: Deploy backend workflow

on:
  push:
    tags:
      - backend

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-2
      ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        id: login
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
